spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/instaweb
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file:
#  dir: D:/Works/devTools/uploaded/
  dir: /Users/lsh/Projects/uploaded/