spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/instaweb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  file.dir: D:/Works/devTools/uploaded/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace